import Link from 'next/link'

export function SiteFooter() {
  return (
    <footer className="relative border-t border-border">
      <div className="mx-auto flex max-w-[1400px] flex-col gap-10 px-5 py-14 md:flex-row md:items-end md:justify-between md:px-10">
        <div>
          <p className="font-mono text-sm font-semibold uppercase tracking-[0.42em]">Clarix</p>
          <p className="mt-4 max-w-sm text-sm leading-relaxed text-muted-foreground">
            Super-resolution mapping for medium-resolution satellite imagery.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-x-8 gap-y-4">
          {[
            { label: 'Technology', href: '/#technology' },
            { label: 'Workflow', href: '/#workflow' },
            { label: 'Results', href: '/#results' },
            { label: 'About', href: '/#about' },
            { label: 'Start Analysis', href: '/analysis' },
          ].map((item) => (
            <Link
              key={item.label}
              href={item.href}
              className="font-mono text-[0.65rem] uppercase tracking-[0.2em] text-muted-foreground transition-colors hover:text-foreground"
            >
              {item.label}
            </Link>
          ))}
        </div>
      </div>

      <div className="mx-auto max-w-[1400px] border-t border-border px-5 py-6 md:px-10">
        <p className="font-mono text-[0.6rem] uppercase tracking-[0.22em] text-muted-foreground/60">
          CLARIX — research interface · Outputs are generated by the connected processing pipeline
        </p>
      </div>
    </footer>
  )
}
